Repository nextcloud/notify_push, pull requests merged in 2024-07, with the labels that each got.

#476 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#481 Add app icon
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  img/app-dark.svg
  img/app.svg
Labels: 3. to review

#482 Migrate to toml
  .github/workflows/reuse.yml
  .reuse/dep5
  REUSE.toml
Labels: 3. to review, technical debt

#483 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#485 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#489 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/psalm-matrix.yml.patch
  .github/workflows/psalm-matrix.yml.patch.license
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, automated, 3. to review

#492 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
