Repository nextcloud/notify_push, pull requests merged in 2025-02, with the labels that each got.

#564 Command\Setup: s/trough/through/
  lib/Command/Setup.php
Labels: 3. to review, feedback-requested

#498 [main] Update nextcloud/ocp dependency
  .github/workflows/update-nextcloud-ocp.yml
  composer.lock
Labels: dependencies, 3. to review

#513 chore: update workflows from templates
  .github/CODEOWNERS
  .github/workflows/appstore-build-publish.yml
  .github/workflows/appstore-build-publish.yml.patch
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-mysql.yml.patch
  .github/workflows/phpunit-mysql.yml.patch.license
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/psalm-matrix.yml.patch
  .github/workflows/psalm-matrix.yml.patch.license
  .github/workflows/reuse.yml
  REUSE.toml
  psalm.xml
Labels: dependencies, automated, 3. to review
